### ISSUE TITLE
Rename Mereti 768 to 1024.

### ISSUE THREAD

**Issue by 10010101001** [Darcman99/Sarcina#19]
This will make the naming scheme (double the last number) much more consistent. e.g
8,16,32,64,128,256,512,1024
instead of
8,16,32,64,128,256,512,768

**Comment by Darcman99** [comment]
It was named 768 instead of 1024 because it didn't look quite enough to be considered a next step in the Meretis 'evolution', but seeing as no other of the Meretis ships use number designations that are not doubles of the previous, it makes no sense for 768 to be used, corrected to 1024.

Thank you for raising this issue.
